// A read-only SQLite reader: enough to pull whole tables out of the collection
// database inside an Anki `.apkg`. Not a query engine — it walks a table's
// b-tree and hands back every row.
//
// Written by hand rather than pulling in sql.js because that is 1.2 MB of WASM,
// which in an offline-first PWA has to be precached for every user whether or
// not they ever import a deck. This is a few hundred lines with no dependency
// and no runtime download.
//
// Pure — no DOM, no storage — so it can be tested against fixtures generated by
// Node's built-in `node:sqlite`.
//
// Format reference: https://sqlite.org/fileformat2.html

export type SqlValue = number | string | Uint8Array | null;
export type Table = { columns: string[]; rows: SqlValue[][] };

const MAGIC = "SQLite format 3\0";

// B-tree page types. Ordinary tables are the table pair; a WITHOUT ROWID table —
// Anki's `fields` and `templates` are two — is stored as an index b-tree, so
// reading only table pages would report those as empty.
const INDEX_INTERIOR = 0x02;
const TABLE_INTERIOR = 0x05;
const INDEX_LEAF = 0x0a;
const TABLE_LEAF = 0x0d;

type Db = {
  bytes: Uint8Array;
  pageSize: number;
  // Page size minus the reserved tail some databases keep; every payload
  // calculation is against this, not the raw page size.
  usable: number;
  decode: (b: Uint8Array) => string;
};

// SQLite varints are big-endian, 1–9 bytes: the first eight contribute seven
// bits each, the ninth all eight. Accumulated by multiplication rather than
// shifts, since `<<` truncates to 32 bits and rowids are 64-bit. Values above
// 2^53 lose precision, which no Anki column reaches (ids are epoch milliseconds).
function varint(bytes: Uint8Array, pos: number): [value: number, next: number] {
  let value = 0;
  for (let i = 0; i < 8; i++) {
    const byte = bytes[pos + i];
    if (byte < 0x80) return [value * 128 + byte, pos + i + 1];
    value = value * 128 + (byte & 0x7f);
  }
  return [value * 256 + bytes[pos + 8], pos + 9];
}

// Pages are numbered from 1.
function page(db: Db, n: number): Uint8Array {
  const start = (n - 1) * db.pageSize;
  if (n < 1 || start + db.pageSize > db.bytes.length) {
    throw new Error("The database file is truncated.");
  }
  return db.bytes.subarray(start, start + db.pageSize);
}

function open(bytes: Uint8Array): Db {
  const magic = new TextDecoder("latin1").decode(bytes.subarray(0, 16));
  if (magic !== MAGIC) throw new Error("Not a SQLite database.");

  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  // A stored page size of 1 means 65536, which doesn't fit the u16 field.
  const raw = view.getUint16(16);
  const pageSize = raw === 1 ? 65536 : raw;

  // Anki writes UTF-8; the other two are handled because the header allows them
  // and guessing wrong produces silent mojibake rather than an error.
  const encoding = view.getUint32(56);
  const decoder = new TextDecoder(
    encoding === 2 ? "utf-16le" : encoding === 3 ? "utf-16be" : "utf-8",
  );
  return {
    bytes,
    pageSize,
    usable: pageSize - bytes[20],
    decode: (b) => decoder.decode(b),
  };
}

// --- Payload ----------------------------------------------------------------

// A cell keeps as much payload as fits on its page and spills the rest onto a
// chain of overflow pages. The split point is not "whatever is left" — it comes
// from the formula in the file format spec, and getting it wrong reads garbage
// out of the middle of a long note. Index pages keep less locally than table
// pages do, so that they can still fan out.
function readPayload(
  db: Db,
  pageBytes: Uint8Array,
  offset: number,
  size: number,
  isIndex: boolean,
): Uint8Array {
  const maxLocal = isIndex
    ? Math.floor(((db.usable - 12) * 64) / 255) - 23
    : db.usable - 35;
  const minLocal = Math.floor(((db.usable - 12) * 32) / 255) - 23;

  let local = size;
  if (size > maxLocal) {
    local = minLocal + ((size - minLocal) % (db.usable - 4));
    if (local > maxLocal) local = minLocal;
  }
  if (local >= size) return pageBytes.subarray(offset, offset + size);

  const out = new Uint8Array(size);
  out.set(pageBytes.subarray(offset, offset + local), 0);
  let written = local;

  // The four bytes after the local part point at the first overflow page; each
  // overflow page then starts with the number of the next, or 0 at the end.
  const view = new DataView(
    pageBytes.buffer,
    pageBytes.byteOffset,
    pageBytes.byteLength,
  );
  let next = view.getUint32(offset + local);
  const seen = new Set<number>();
  while (next !== 0 && written < size) {
    // A corrupt file can point a chain back at itself; without this the import
    // hangs rather than reporting a bad file.
    if (seen.has(next)) throw new Error("The database file is corrupt.");
    seen.add(next);
    const over = page(db, next);
    const chunk = Math.min(size - written, db.usable - 4);
    out.set(over.subarray(4, 4 + chunk), written);
    written += chunk;
    next = new DataView(over.buffer, over.byteOffset, over.byteLength).getUint32(
      0,
    );
  }
  return out;
}

// --- Records ----------------------------------------------------------------

function readInt(bytes: Uint8Array, pos: number, length: number): number {
  // Two's complement: the top bit of the first byte is the sign.
  let value = bytes[pos] & 0x80 ? bytes[pos] - 0x100 : bytes[pos];
  for (let i = 1; i < length; i++) value = value * 256 + bytes[pos + i];
  return value;
}

// A record is a header of serial-type varints followed by the values they
// describe, in the same order.
function readRecord(db: Db, payload: Uint8Array): SqlValue[] {
  const [headerSize, afterSize] = varint(payload, 0);
  const types: number[] = [];
  let p = afterSize;
  while (p < headerSize) {
    const [type, next] = varint(payload, p);
    types.push(type);
    p = next;
  }

  const view = new DataView(
    payload.buffer,
    payload.byteOffset,
    payload.byteLength,
  );
  const values: SqlValue[] = [];
  let body = headerSize;
  for (const type of types) {
    if (type === 0) {
      values.push(null);
    } else if (type >= 1 && type <= 6) {
      const length = type <= 4 ? type : type === 5 ? 6 : 8;
      values.push(readInt(payload, body, length));
      body += length;
    } else if (type === 7) {
      values.push(view.getFloat64(body));
      body += 8;
    } else if (type === 8 || type === 9) {
      values.push(type - 8);
    } else if (type >= 12 && type % 2 === 0) {
      const length = (type - 12) / 2;
      values.push(payload.slice(body, body + length));
      body += length;
    } else if (type >= 13) {
      const length = (type - 13) / 2;
      values.push(db.decode(payload.subarray(body, body + length)));
      body += length;
    } else {
      // 10 and 11 are reserved and never appear in a valid file.
      values.push(null);
    }
  }
  return values;
}

// --- B-tree -----------------------------------------------------------------

type Row = { rowid: number | null; values: SqlValue[] };

// Depth-first, which visits leaves — and so rows — in key order. For a table
// that means rowid order, and Anki's ids are creation timestamps, so it is also
// the order the notes were added in.
function walk(db: Db, root: number, out: Row[], seen: Set<number>): void {
  // Also guards against a corrupt file pointing a subtree back at an ancestor.
  if (seen.has(root)) throw new Error("The database file is corrupt.");
  seen.add(root);

  const bytes = page(db, root);
  // Page 1 carries the 100-byte file header before its b-tree header.
  const base = root === 1 ? 100 : 0;
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const type = bytes[base];
  const interior = type === TABLE_INTERIOR || type === INDEX_INTERIOR;
  const isIndex = type === INDEX_INTERIOR || type === INDEX_LEAF;
  if (!interior && type !== TABLE_LEAF && type !== INDEX_LEAF) return;

  const cells = view.getUint16(base + 3);
  const pointers = base + (interior ? 12 : 8);

  for (let i = 0; i < cells; i++) {
    let p = view.getUint16(pointers + i * 2);
    // An interior cell leads with its left child, which holds every key below
    // this one, so it is visited first.
    if (interior) {
      walk(db, view.getUint32(p), out, seen);
      // A table interior cell is nothing but that pointer and a rowid — the row
      // itself lives on a leaf. An index interior cell also carries a key, and
      // for a WITHOUT ROWID table that key *is* a row, so it has to be read.
      if (type === TABLE_INTERIOR) continue;
      p += 4;
    }

    const [size, afterSize] = varint(bytes, p);
    p = afterSize;
    let rowid: number | null = null;
    if (!isIndex) {
      const [id, afterRowid] = varint(bytes, p);
      rowid = id;
      p = afterRowid;
    }
    out.push({ rowid, values: readRecord(db, readPayload(db, bytes, p, size, isIndex)) });
  }

  // The rightmost subtree has no cell of its own.
  if (interior) walk(db, view.getUint32(base + 8), out, seen);
}

// --- Schema -----------------------------------------------------------------

type Columns = {
  names: string[];
  // Index of the INTEGER PRIMARY KEY column, whose value is the cell's rowid
  // rather than anything in the record. -1 when there isn't one.
  rowid: number;
  // Primary key columns, in key order, for a WITHOUT ROWID table.
  key: string[];
  withoutRowid: boolean;
};

// Column names come from the stored CREATE TABLE, which is the original text —
// Anki's carries a `/* comment */` after most columns, and types and constraints
// bring their own parentheses, so neither a split on commas nor a regex is
// enough on its own.
function parseColumns(sql: string): Columns {
  const clean = sql.replace(/\/\*[\s\S]*?\*\//g, " ").replace(/--[^\n]*/g, " ");
  const open = clean.indexOf("(");
  if (open === -1) return { names: [], rowid: -1, key: [], withoutRowid: false };

  // Split the definition list on top-level commas.
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  let end = clean.length;
  for (let i = open + 1; i < clean.length; i++) {
    const ch = clean[i];
    if (ch === "(") depth++;
    else if (ch === ")") {
      if (depth === 0) {
        end = i;
        break;
      }
      depth--;
    }
    if (ch === "," && depth === 0) {
      parts.push(current);
      current = "";
      continue;
    }
    current += ch;
  }
  parts.push(current);

  const unquote = (text: string) => {
    const quoted = /^(["`[])(.*?)[\]"`]/.exec(text);
    return quoted ? quoted[2] : (/^[A-Za-z_][A-Za-z0-9_$]*/.exec(text)?.[0] ?? "");
  };

  const names: string[] = [];
  const key: string[] = [];
  let rowid = -1;
  for (const part of parts) {
    const text = part.trim();
    if (!text) continue;

    // Table-level constraints share the list with the columns. Only the primary
    // key matters here, and only for a WITHOUT ROWID table, whose records store
    // the key columns first.
    const table = /^primary\s+key\s*\(([^)]*)\)/i.exec(text);
    if (table) {
      key.push(...table[1].split(",").map((c) => unquote(c.trim())));
      continue;
    }
    if (/^(primary|unique|check|foreign|constraint)\b/i.test(text)) continue;

    const name = unquote(text);
    if (!name) continue;
    if (/\bprimary\s+key\b/i.test(text)) {
      key.push(name);
      // `INTEGER PRIMARY KEY` is an alias for the rowid: the record stores NULL
      // there and the real value is the cell's rowid.
      if (/\binteger\s+primary\s+key\b/i.test(text)) rowid = names.length;
    }
    names.push(name);
  }

  return {
    names,
    rowid,
    key,
    withoutRowid: /without\s+rowid/i.test(clean.slice(end)),
  };
}

/**
 * Read every row of one table. Returns null when the table isn't in the file,
 * which callers use to tell Anki's schema versions apart.
 */
export function readTable(bytes: Uint8Array, table: string): Table | null {
  const db = open(bytes);

  // sqlite_schema always lives on page 1: type, name, tbl_name, rootpage, sql.
  const schema: Row[] = [];
  walk(db, 1, schema, new Set());
  const entry = schema.find(
    (r) => r.values[0] === "table" && r.values[1] === table,
  );
  if (!entry) return null;

  const { names, rowid, key, withoutRowid } = parseColumns(
    String(entry.values[4] ?? ""),
  );
  const found: Row[] = [];
  walk(db, Number(entry.values[3]), found, new Set());

  // A WITHOUT ROWID table is an index whose records hold the key columns first
  // and the rest in declared order — not declared order throughout. Left
  // unmapped its columns silently come back shuffled.
  const order = withoutRowid
    ? [
        ...key.map((k) => names.indexOf(k)),
        ...names.map((_, i) => i).filter((i) => !key.includes(names[i])),
      ]
    : null;

  return {
    columns: names,
    rows: found.map(({ rowid: id, values }) => {
      if (!order) {
        if (rowid >= 0) values[rowid] = id;
        return values;
      }
      const row: SqlValue[] = new Array(names.length).fill(null);
      order.forEach((target, source) => {
        if (target >= 0) row[target] = values[source] ?? null;
      });
      return row;
    }),
  };
}
